// Generated by CoffeeScript 1.9.1
(function() {
  require('./tests/h2o.test.js');

  require('./examples/diagnostics.js');

  require('./examples/metadata.js');

  require('./examples/airlines.js');

}).call(this);
