// Generated by CoffeeScript 1.9.1
(function() {
  var h2o, h2ojs, test;

  h2ojs = require('./../h2o.js');

  test = require('tape');

  h2o = h2ojs.connect();

  test('getSchemas', function(t) {
    return h2o.getSchemas(function(error, schemas) {
      if (error) {
        return t.end(error);
      } else {
        console.log('The list of all H2O Schemas:');
        h2o.dump(schemas);
        return t.end();
      }
    });
  });

  test('getSchema', function(t) {
    return h2o.getSchema('CloudV1', function(error, schema) {
      if (error) {
        return t.end(error);
      } else {
        console.log('The schema for CloudV1:');
        h2o.dump(schema);
        return t.end();
      }
    });
  });

  test('getEndpoints', function(t) {
    return h2o.getEndpoints(function(error, endpoints) {
      if (error) {
        return t.end(error);
      } else {
        console.log('The list of all H2O API endpoints:');
        h2o.dump(endpoints);
        return t.end();
      }
    });
  });

  test('getEndpoint', function(t) {
    return h2o.getEndpoint(10, function(error, endpoint) {
      if (error) {
        return t.end(error);
      } else {
        console.log('The endpoint at index #10:');
        h2o.dump(endpoint);
        return t.end();
      }
    });
  });

}).call(this);
